#!/bin/bash

# ORCARE MIGRATION QUICK REFERENCE CARD
# MongoDB → Supabase PostgreSQL
# 
# Usage: Save this as migration-checklist.sh
# Run: bash migration-checklist.sh
# Or: Read as step-by-step guide

echo "=========================================="
echo "ORCare MongoDB → Supabase Migration"
echo "==========================================="
echo ""

# PHASE 1: SETUP
echo "📋 PHASE 1: SETUP (Check off as you complete)"
echo ""
echo "[ ] Step 1: Create Supabase project"
echo "    → Visit https://supabase.com"
echo "    → Create new project"
echo "    → Wait for database initialization"
echo ""
echo "[ ] Step 2: Get Supabase credentials"
echo "    → Go to Settings → API"
echo "    → Copy SUPABASE_URL"
echo "    → Copy SERVICE_ROLE_KEY"
echo ""
echo "[ ] Step 3: Create PostgreSQL schema"
echo "    → Copy migrations/001_create_tables.sql"
echo "    → Go to Supabase SQL Editor → New Query"
echo "    → Paste entire SQL file"
echo "    → Click Run"
echo ""
echo "[ ] Step 4: Verify tables created"
echo "    → Go to Supabase Table Editor"
echo "    → Should see 8 tables: users, chat_sessions, chat_messages,"
echo "      diseases, learning_categories, learning_modules, quizzes, feedbacks"
echo ""

echo "=========================================="
echo "📝 PHASE 2: CODE CHANGES"
echo "=========================================="
echo ""
echo "[ ] Step 5: Update .env file"
echo "    Copy: .env.example → .env"
echo "    Edit .env and add:"
echo "    SUPABASE_URL=https://..."
echo "    SUPABASE_SERVICE_ROLE_KEY=your-key"
echo ""
echo "[ ] Step 6: Install dependencies"
echo "    Run: npm install @supabase/supabase-js"
echo "    Run: npm uninstall mongoose mongodb"
echo "    Run: npm install"
echo ""
echo "[ ] Step 7: Update server.js"
echo "    Change: const connectDB = require('./config/db');"
echo "    To: const { testConnection } = require('./config/supabase');"
echo ""
echo "[ ] Step 8: Update routes to use Supabase controllers"
echo "    authRoutes.js:"
echo "    Change: require('./controllers/authController')"
echo "    To: require('./controllers/authController_supabase')"
echo ""
echo "    Same for:"
echo "    - chatController → chatController_supabase"
echo "    - userController → userController_supabase"
echo "    - contentController → contentController_supabase"
echo "    - quizController → quizController_supabase"
echo ""
echo "[ ] Step 9: Update auth middleware in all route files"
echo "    Change: require('../middleware/authMiddleware')"
echo "    To: require('../middleware/authMiddleware_supabase')"
echo ""

echo "=========================================="
echo "🔄 PHASE 3: DATA MIGRATION"
echo "=========================================="
echo ""
echo "[ ] Step 10: Run migration script"
echo "    Run: node scripts/migrateMongoToSupabase.js"
echo ""
echo "    Wait for output like:"
echo "    ✅ Migrated 50 users"
echo "    ✅ Migrated 30 diseases"
echo "    ✅ Migrated 20 learning categories"
echo "    ✅ Migrated 100 quizzes"
echo "    etc."
echo ""
echo "[ ] Step 11: Verify data in Supabase"
echo "    Go to Supabase SQL Editor"
echo "    Run each query:"
echo "    SELECT COUNT(*) FROM users;"
echo "    SELECT COUNT(*) FROM diseases;"
echo "    SELECT COUNT(*) FROM chat_sessions;"
echo "    SELECT COUNT(*) FROM learning_categories;"
echo "    SELECT COUNT(*) FROM quizzes;"
echo "    SELECT COUNT(*) FROM feedbacks;"
echo ""
echo "    Compare counts with your MongoDB database"
echo ""

echo "=========================================="
echo "🧪 PHASE 4: TESTING"
echo "=========================================="
echo ""
echo "[ ] Step 12: Start development server"
echo "    Run: npm run dev"
echo ""
echo "[ ] Step 13: Test authentication"
echo "    POST http://localhost:3000/api/auth/register"
echo "    {\"name\":\"Test\",\"email\":\"test@example.com\",\"password\":\"password123\"}"
echo ""
echo "    Should see: User created, verification email sent"
echo ""
echo "[ ] Step 14: Test content endpoints"
echo "    GET http://localhost:3000/api/content/diseases"
echo "    Should return: Array of diseases"
echo ""
echo "[ ] Step 15: Test user endpoints (with auth token)"
echo "    GET http://localhost:3000/api/users/profile"
echo "    Header: Authorization: Bearer <token>"
echo "    Should return: User profile"
echo ""
echo "[ ] Step 16: Test chat"
echo "    POST http://localhost:3000/api/chat/send"
echo "    Header: Authorization: Bearer <token>"
echo "    Body: {\"sessionId\":\"session1\",\"message\":\"Hello\"}"
echo "    Should return: AI response"
echo ""
echo "[ ] Step 17: Test quiz"
echo "    POST http://localhost:3000/api/quiz/submit"
echo "    Header: Authorization: Bearer <token>"
echo "    Body: {\"questions\":[],\"score\":85}"
echo "    Should return: Quiz saved"
echo ""

echo "=========================================="
echo "🚀 PHASE 5: DEPLOYMENT"
echo "=========================================="
echo ""
echo "[ ] Step 18: Clean up code"
echo "    Remove: All /models/*.js files (old MongoDB models)"
echo "    Remove: /config/db.js (old MongoDB config)"
echo "    Keep: /migrations/ folder (as reference)"
echo ""
echo "[ ] Step 19: Verify no MongoDB references"
echo "    Run: grep -r \"mongoose\" ."
echo "    Run: grep -r \"MongoDB\" ."
echo "    Should return: Nothing (or only comments)"
echo ""
echo "[ ] Step 20: Final test"
echo "    Run: npm run dev"
echo "    Test all endpoints one more time"
echo ""
echo "[ ] Step 21: Deploy to staging"
echo "    For Render:"
echo "    - Connect GitHub repo"
echo "    - Set environment variables in dashboard"
echo "    - Deploy"
echo ""
echo "[ ] Step 22: Test in staging"
echo "    Run all endpoint tests against staging URL"
echo ""
echo "[ ] Step 23: Deploy to production"
echo "    Promote from staging OR"
echo "    Deploy main branch to production"
echo ""

echo "=========================================="
echo "✅ SUCCESS CHECKLIST"
echo "=========================================="
echo ""
echo "✓ Tables created in Supabase"
echo "✓ Data migrated from MongoDB"
echo "✓ Authentication working"
echo "✓ Chat functionality working"
echo "✓ Quiz submissions working"
echo "✓ User profiles updating"
echo "✓ Content retrieval working"
echo "✓ No MongoDB references in code"
echo "✓ Deployed to production"
echo "✓ All endpoints responding < 200ms"
echo "✓ Error logs clean"
echo ""

echo "=========================================="
echo "📞 TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "❌ 'Cannot find module @supabase/supabase-js'"
echo "   → Run: npm install @supabase/supabase-js"
echo ""
echo "❌ 'Supabase connection failed'"
echo "   → Check SUPABASE_URL and SERVICE_ROLE_KEY in .env"
echo "   → Make sure tables were created"
echo "   → Check network access (firewall)"
echo ""
echo "❌ 'Foreign key constraint violation'"
echo "   → User doesn't exist when creating chat/quiz"
echo "   → Ensure migration script completed successfully"
echo ""
echo "❌ 'Email not sending'"
echo "   → Check BREVO_SMTP credentials in .env"
echo "   → Verify From_EMAIL matches Brevo account"
echo ""
echo "❌ 'JWT verification failed'"
echo "   → Make sure JWT_SECRET is same in .env"
echo "   → Token may have expired (default 30 days)"
echo ""

echo "=========================================="
echo "For detailed help, see:"
echo "   - MIGRATION_GUIDE.md (complete step-by-step)"
echo "   - MIGRATION_SUMMARY.md (files & schema changes)"
echo ""
echo "Good luck! 🚀"
echo "=========================================="
