[build]
builder = "dockerfile"
dockerfilePath = "fastapi_backend/Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health/"
restartPolicyType = "on_failure"
